In [4]:
from sklearn.feature_extraction.text import TfidfVectorizer
text = ['hello, good morning' ]

In [39]:
vect = TfidfVectorizer()

In [40]:
vect.fit(text)

TfidfVectorizer()

In [41]:
## TF will count the frequency of word in each document. and IDF 
print(vect.idf_)

[1. 1. 1.]

In [42]:
print(vect.vocabulary_)

{'hello': 1, 'good': 0, 'morning': 2}

In [43]:
example = text[0]
example

'hello, good morning'

In [44]:
example = vect.transform([example])
print(example.toarray())

[[0.57735027 0.57735027 0.57735027]]

In [2]:
import pandas as pd

In [3]:
dataframe = pd.read_csv('cleaned_dataset.csv')
dataframe.head()

,id,statement,description,rating
0,6771.0,Dawn dish soap contains ammonia even though it...,Could Mixing Dawn Dish Soap with Clorox Bleach...,mixture
1,2468.0,Is blue light harmful to our eyes?,It seems reasonable to reduce exposure to blue...,unproven
2,1929.0,Are the 'Winter Blues' real?,"I've recently <a href=""https://www.sciencedail...",TRUE
3,1872.0,Is air pollution linked to greater risk of dem...,"<a href=""https://www.theguardian.com/environme...",TRUE
4,1956.0,Can eccentric exercises cause human hyperplasia?,With concentric regular exercises muscle hyper...,unproven

In [4]:
dataframe['rating'] = dataframe['rating'].replace('mixture', 'TRUE')
dataframe['rating'] = dataframe['rating'].replace('unproven', 'TRUE')
dataframe['rating'] = dataframe['rating'].replace('mostly-true', 'TRUE')
dataframe['rating'] = dataframe['rating'].replace('mostly-false', 'FALSE')

In [8]:
dataframe.head()

,id,statement,description,rating
0,6771.0,Dawn dish soap contains ammonia even though it...,Could Mixing Dawn Dish Soap with Clorox Bleach...,TRUE
1,2468.0,Is blue light harmful to our eyes?,It seems reasonable to reduce exposure to blue...,TRUE
2,1929.0,Are the 'Winter Blues' real?,"I've recently <a href=""https://www.sciencedail...",TRUE
3,1872.0,Is air pollution linked to greater risk of dem...,"<a href=""https://www.theguardian.com/environme...",TRUE
4,1956.0,Can eccentric exercises cause human hyperplasia?,With concentric regular exercises muscle hyper...,TRUE

In [4]:
dataframe.rating.value_counts()

rating
FALSE    353
TRUE     330
Name: count, dtype: int64

In [16]:
x = dataframe['statement']
y = dataframe['rating']

In [17]:
x

0      Dawn dish soap contains ammonia even though it...
1                     Is blue light harmful to our eyes?
2                           Are the 'Winter Blues' real?
3      Is air pollution linked to greater risk of dem...
4       Can eccentric exercises cause human hyperplasia?
                             ...
678               (noni|morinda citrifolia) treat cancer
679    (nonotus obliquus|chaga|Boletus obliquus|Polyp...
680    (orgone|orgonite|cloudbuster|Wilhelm Reich) tr...
681    (oxygen therapy|hyperbaric|hbot|O2 therapy|sup...
682    (Therapeutic touch|non-contact therapeutic tou...
Name: statement, Length: 683, dtype: object

In [18]:
y

0       TRUE
1       TRUE
2       TRUE
3       TRUE
4       TRUE
       ...
678    FALSE
679    FALSE
680    FALSE
681    FALSE
682    FALSE
Name: rating, Length: 683, dtype: object

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [20]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
y_train

312    FALSE
202     TRUE
263     TRUE
395    FALSE
101     TRUE
       ...
9       TRUE
359     TRUE
192    FALSE
629    FALSE
559    FALSE
Name: rating, Length: 546, dtype: object

In [21]:
y_train

312    FALSE
202     TRUE
263     TRUE
395    FALSE
101     TRUE
       ...
9       TRUE
359     TRUE
192    FALSE
629    FALSE
559    FALSE
Name: rating, Length: 546, dtype: object

In [22]:
tfvect = TfidfVectorizer(stop_words='english',max_df=0.7)
tfid_x_train = tfvect.fit_transform(x_train)
tfid_x_test = tfvect.transform(x_test)

* max_df = 0.50 means "ignore terms that appear in more than 50% of the documents".
* max_df = 25 means "ignore terms that appear in more than 25 documents".

In [23]:
classifier = PassiveAggressiveClassifier(max_iter=50)
classifier.fit(tfid_x_train,y_train)

PassiveAggressiveClassifier(max_iter=50)

In [24]:
y_pred = classifier.predict(tfid_x_test)
score = accuracy_score(y_test,y_pred)
print(f'Accuracy: {round(score*100,2)}%')

Accuracy: 74.45%

In [26]:
cf = confusion_matrix(y_test,y_pred, labels=['TRUE','FALSE'])
print(cf)

[[55 18]
 [17 47]]

In [31]:
def misinfo_det(info):
    input_data = [info]
    vectorized_input_data = tfvect.transform(input_data)
    prediction = classifier.predict(vectorized_input_data)
    print(prediction)

In [32]:
misinfo_det('Is insomnia permanent?')

['FALSE']

In [33]:
import pickle
pickle.dump(classifier,open('newmodel.pkl', 'wb'))

In [34]:
# load the model from disk
loaded_model = pickle.load(open('newmodel.pkl', 'rb'))

In [35]:
def misinfo_det1(info):
    input_data = [info]
    vectorized_input_data = tfvect.transform(input_data)
    prediction = loaded_model.predict(vectorized_input_data)
    print(prediction)

In [37]:
misinfo_det1("Can diet impact sleep?")

['TRUE']

RNN Implementation

In [5]:
import tensorflow as tf
print(tf.__version__)

2.13.0-rc2

In [6]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
from keras.layers import Dense, Embedding, LSTM, SpatialDropout1D
from keras.models import Sequential
from sklearn.feature_extraction.text import CountVectorizer
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping

In [7]:
num_of_categories = 1000
shuffled = dataframe.reindex(np.random.permutation(dataframe.index))
TRUE = shuffled[shuffled['rating'] == 'TRUE'][:num_of_categories]
FALSE = shuffled[shuffled['rating'] == 'FALSE'][:num_of_categories]
concated = pd.concat([TRUE,FALSE], ignore_index=True)
#Shuffle the dataset
concated = concated.reindex(np.random.permutation(concated.index))
concated['LABEL'] = 0

In [8]:
concated.loc[concated['rating'] == 'TRUE', 'LABEL'] = 0
concated.loc[concated['rating'] == 'FALSE', 'LABEL'] = 1
print(concated['LABEL'][:10])
labels = to_categorical(concated['LABEL'], num_classes=2)
print(labels[:10])
if 'rating' in concated.keys():
    concated.drop(['rating'], axis=1)

482    1
471    1
199    0
423    1
118    0
290    0
125    0
509    1
23     0
521    1
Name: LABEL, dtype: int64
[[0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]]

In [9]:
n_most_common_words = 8000
max_len = 130
tokenizer = Tokenizer(num_words=n_most_common_words, filters='!"#$%&()*+,-./:;<=>?@[\]^_`{|}~', lower=True)
tokenizer.fit_on_texts(concated['statement'].values)
sequences = tokenizer.texts_to_sequences(concated['statement'].values)
word_index = tokenizer.word_index
print('Found %s unique tokens.' % len(word_index))

X = pad_sequences(sequences, maxlen=max_len)

Found 2548 unique tokens.

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X , labels, test_size=0.25, random_state=42)

In [11]:
epochs = 10
emb_dim = 128
batch_size = 256
labels[:2]

array([[0., 1.],
       [0., 1.]], dtype=float32)

In [12]:
print((X_train.shape, y_train.shape, X_test.shape, y_test.shape))

model = Sequential()
model.add(Embedding(n_most_common_words, emb_dim, input_length=X.shape[1]))
model.add(SpatialDropout1D(0.7))
model.add(LSTM(64, dropout=0.7, recurrent_dropout=0.7))
model.add(Dense(2, activation='softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])
print(model.summary())
history = model.fit(X_train, y_train, epochs=10, batch_size=50,validation_split=0.2,callbacks=[EarlyStopping(monitor='val_loss',patience=3, min_delta=0)])

((512, 130), (512, 2), (171, 130), (171, 2))
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 embedding (Embedding)       (None, 130, 128)          1024000

 spatial_dropout1d (Spatial  (None, 130, 128)          0
 Dropout1D)

 lstm (LSTM)                 (None, 64)                49408

 dense (Dense)               (None, 2)                 130

=================================================================
Total params: 1073538 (4.10 MB)
Trainable params: 1073538 (4.10 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None
Epoch 1/10
9/9 [==============================] - 5s 173ms/step - loss: 0.6883 - acc: 0.5477 - val_loss: 0.6799 - val_acc: 0.6990
Epoch 2/10
9/9 [==============================] - 1s 134ms/step - loss: 0.6723 - acc: 0.6308 - val_loss: 0.6704 - val_acc: 0.5437
Epoch 3/10
9/9 [==============================] - 1s 131ms/step - loss: 0.6515 - acc: 0.6504 - val_loss: 0.6495 - val_acc: 0.6602
Epoch 4/10
9/9 [==============================] - 1s 138ms/step - loss: 0.6267 - acc: 0.6846 - val_loss: 0.6175 - val_acc: 0.7282
Epoch 5/10
9/9 [==============================] - 1s 138ms/step - loss: 0.5824 - acc: 0.7555 - val_loss: 0.5829 - val_acc: 0.7379
Epoch 6/10
9/9 [==============================] - 1s 127ms/step - loss: 0.5560 - acc: 0.7311 - val_loss: 0.5450 - val_acc: 0.7379
Epoch 7/10
9/9 [==============================] - 1s 132ms/step - loss: 0.5071 - acc: 0.7628 - val_loss: 0.5087 - val_acc: 0.7767
Epoch 8/10
9/9 [==============================] - 1s 131ms/step - loss: 0.4710 - acc: 0.7922 - val_loss: 0.4760 - val_acc: 0.7961
Epoch 9/10
9/9 [==============================] - 1s 133ms/step - loss: 0.4141 - acc: 0.8362 - val_loss: 0.4495 - val_acc: 0.8350
Epoch 10/10
9/9 [==============================] - 1s 134ms/step - loss: 0.3453 - acc: 0.8826 - val_loss: 0.4115 - val_acc: 0.8350

In [13]:
accr = model.evaluate(X_test,y_test)
print('Test set\n  Loss: {:0.3f}\n  Accuracy: {:0.3f}'.format(accr[0],accr[1]))

6/6 [==============================] - 0s 16ms/step - loss: 0.4358 - acc: 0.8070
Test set
  Loss: 0.436
  Accuracy: 0.807

In [16]:
from keras.models import Sequential
from keras.layers import Embedding, SpatialDropout1D, LSTM, Dense
from keras.utils import plot_model

# Define the model architecture
model = Sequential()
model.add(Embedding(n_most_common_words, emb_dim, input_length=max_len))
model.add(SpatialDropout1D(0.7))
model.add(LSTM(64, dropout=0.7, recurrent_dropout=0.7))
model.add(Dense(2, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['acc'])

# Generate the neural network diagram
plot_model(model, to_file='neural_network_diagram.png', show_shapes=True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.

In [16]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import confusion_matrix
# Evaluation Metrics
y_pred = model.predict(X_test)
y_pred_classes = np.argmax(y_pred, axis=1)
y_test_classes = np.argmax(y_test, axis=1)

precision, recall, f1_score, support = precision_recall_fscore_support(y_test_classes, y_pred_classes, average='weighted')
print("Precision: {:.2f}".format(precision))
print("Recall: {:.2f}".format(recall))
print("F1 Score: {:.2f}".format(f1_score))
print("Support: {}".format(support))

6/6 [==============================] - 0s 15ms/step
Precision: 0.89
Recall: 0.88
F1 Score: 0.88
Support: None

In [20]:
y_pred

array([[0.07344146, 0.92655855],
       [0.9593414 , 0.04065856],
       [0.19852361, 0.8014764 ],
       [0.9435826 , 0.05641738],
       [0.8380105 , 0.16198957],
       [0.72325367, 0.2767463 ],
       [0.62320924, 0.37679076],
       [0.1251723 , 0.8748277 ],
       [0.17144302, 0.828557  ],
       [0.17436695, 0.825633  ],
       [0.8336175 , 0.16638248],
       [0.15180837, 0.84819156],
       [0.87199533, 0.12800466],
       [0.12841009, 0.8715899 ],
       [0.29039648, 0.70960355],
       [0.9050143 , 0.09498571],
       [0.89465314, 0.10534686],
       [0.89408743, 0.10591257],
       [0.6688567 , 0.33114326],
       [0.68036073, 0.31963924],
       [0.09888972, 0.9011103 ],
       [0.10218637, 0.89781356],
       [0.7715207 , 0.2284793 ],
       [0.9116031 , 0.08839689],
       [0.38000423, 0.6199958 ],
       [0.12387266, 0.8761273 ],
       [0.29163417, 0.70836586],
       [0.84735656, 0.15264344],
       [0.94148546, 0.05851451],
       [0.30576628, 0.6942337 ],
       [0.87703836, 0.12296164],
       [0.23270504, 0.76729494],
       [0.17950688, 0.82049316],
       [0.57869333, 0.42130664],
       [0.7336992 , 0.26630083],
       [0.7040317 , 0.2959683 ],
       [0.8443344 , 0.15566552],
       [0.13559113, 0.86440885],
       [0.25091648, 0.7490835 ],
       [0.6014607 , 0.3985393 ],
       [0.84533405, 0.15466596],
       [0.22621922, 0.77378076],
       [0.17472425, 0.8252758 ],
       [0.3940201 , 0.6059799 ],
       [0.40009722, 0.59990275],
       [0.7681046 , 0.23189536],
       [0.736056  , 0.26394403],
       [0.8778974 , 0.1221026 ],
       [0.07119004, 0.9288099 ],
       [0.6231233 , 0.37687665],
       [0.12476334, 0.8752367 ],
       [0.27015492, 0.7298451 ],
       [0.3894597 , 0.6105403 ],
       [0.8882443 , 0.11175573],
       [0.21823958, 0.7817604 ],
       [0.23771699, 0.7622831 ],
       [0.08438889, 0.9156111 ],
       [0.6694375 , 0.3305625 ],
       [0.85489905, 0.1451009 ],
       [0.13118578, 0.86881423],
       [0.30447212, 0.6955278 ],
       [0.9179516 , 0.08204839],
       [0.9041244 , 0.09587565],
       [0.22278446, 0.7772155 ],
       [0.25640827, 0.74359167],
       [0.8996302 , 0.1003698 ],
       [0.2370978 , 0.7629022 ],
       [0.03442251, 0.9655775 ],
       [0.18798058, 0.8120194 ],
       [0.92623055, 0.07376944],
       [0.3894597 , 0.6105403 ],
       [0.78933877, 0.21066125],
       [0.05287115, 0.9471289 ],
       [0.1328247 , 0.8671753 ],
       [0.125959  , 0.874041  ],
       [0.17729339, 0.82270664],
       [0.85483885, 0.14516114],
       [0.0737789 , 0.92622113],
       [0.6237398 , 0.37626013],
       [0.28299966, 0.71700037],
       [0.12482429, 0.8751757 ],
       [0.728376  , 0.271624  ],
       [0.17258126, 0.82741874],
       [0.12661967, 0.87338036],
       [0.2259144 , 0.77408564],
       [0.6311023 , 0.36889768],
       [0.8557804 , 0.1442196 ],
       [0.51584566, 0.48415428],
       [0.15753792, 0.84246206],
       [0.18768121, 0.81231874],
       [0.88213944, 0.11786059],
       [0.77687544, 0.22312455],
       [0.8981725 , 0.10182751],
       [0.23746412, 0.7625359 ],
       [0.90110326, 0.09889673],
       [0.0861708 , 0.91382927],
       [0.8773907 , 0.12260927],
       [0.7132817 , 0.2867183 ],
       [0.13387664, 0.86612344],
       [0.49793506, 0.50206494],
       [0.29824698, 0.701753  ],
       [0.13386302, 0.866137  ],
       [0.1299696 , 0.8700304 ],
       [0.08435756, 0.91564244],
       [0.1924218 , 0.8075782 ],
       [0.74770063, 0.25229937],
       [0.74422026, 0.25577974],
       [0.334654  , 0.665346  ],
       [0.891465  , 0.108535  ],
       [0.25592262, 0.7440774 ],
       [0.9021916 , 0.09780844],
       [0.470766  , 0.529234  ],
       [0.36195758, 0.63804245],
       [0.8750338 , 0.12496623],
       [0.22040194, 0.7795981 ],
       [0.38751453, 0.61248547],
       [0.8602917 , 0.13970836],
       [0.10342562, 0.8965744 ],
       [0.13593274, 0.86406726],
       [0.17470223, 0.8252978 ],
       [0.28744677, 0.71255326],
       [0.80455613, 0.19544387],
       [0.7043856 , 0.29561445],
       [0.38240945, 0.61759055],
       [0.885919  , 0.11408106],
       [0.15883985, 0.8411602 ],
       [0.17969142, 0.82030857],
       [0.12208654, 0.8779135 ],
       [0.8008037 , 0.19919623],
       [0.95674586, 0.04325413],
       [0.26982993, 0.73017   ],
       [0.9403275 , 0.05967249],
       [0.40502036, 0.59497964],
       [0.1152003 , 0.88479966],
       [0.8090472 , 0.19095272],
       [0.7610627 , 0.23893726],
       [0.76371497, 0.23628499],
       [0.11021218, 0.8897878 ],
       [0.5378849 , 0.4621151 ],
       [0.87243396, 0.12756607],
       [0.75292146, 0.24707852],
       [0.3152316 , 0.6847684 ],
       [0.8654509 , 0.13454908],
       [0.512687  , 0.48731297],
       [0.8945573 , 0.10544269],
       [0.9198966 , 0.08010338],
       [0.93181485, 0.06818519],
       [0.9116556 , 0.08834439],
       [0.9427011 , 0.05729884],
       [0.06460582, 0.9353941 ],
       [0.04638081, 0.9536191 ],
       [0.8838314 , 0.11616858],
       [0.92939824, 0.07060183],
       [0.06609241, 0.93390757],
       [0.42946002, 0.5705401 ],
       [0.9026079 , 0.09739203],
       [0.22278446, 0.7772155 ],
       [0.55706346, 0.44293657],
       [0.8880563 , 0.11194374],
       [0.92173773, 0.07826231],
       [0.07668547, 0.9233145 ],
       [0.88053596, 0.11946405],
       [0.9324761 , 0.06752392],
       [0.12090813, 0.8790919 ],
       [0.14070061, 0.8592994 ],
       [0.947211  , 0.05278891],
       [0.7170795 , 0.28292048],
       [0.40661848, 0.5933816 ],
       [0.5934507 , 0.40654922],
       [0.60644805, 0.3935519 ],
       [0.8079904 , 0.1920096 ]], dtype=float32)

In [45]:
y_test

array([[0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [42]:
txt = ["Does taking apple cider vinegar as a supplement have any real health benefits?"]
seq = tokenizer.texts_to_sequences(txt)
padded = pad_sequences(seq, maxlen=max_len)
pred = model.predict(padded)
labels = ['TRUE', 'FALSE']
print(labels[np.argmax(pred)])

1/1 [==============================] - 0s 221ms/step
TRUE

In [113]:
y_pred_probabilities = model.predict(X_test)
y_pred = np.argmax(y_pred_probabilities, axis=1).astype("int64")
labels = to_categorical(concated['LABEL'], num_classes=2)
labels[labels == [1.,0.]]= [0]
labels[labels == [0.,1.]]= [1]
y_true = labels

6/6 [==============================] - 0s 13ms/step

In [114]:
y_true

array([[1., 0.],
       [1., 0.],
       [1., 1.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]], dtype=float32)

In [100]:
y_pred

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0], dtype=int64)

In [14]:
def rnn_det(txt):
    input_data = [txt]
    seq = tokenizer.texts_to_sequences(input_data)
    padded = pad_sequences(seq)
    prediction = model.predict(padded)
    labels = ['TRUE', 'FALSE']
    print(labels[np.argmax(prediction)])

In [15]:
rnn_det("Antibodies for the common cold produce a positive COVID-19 test; false-positive results from COVID-19 antibody testing are behind the COVID-19 cases reported in the U.S.")

1/1 [==============================] - 0s 236ms/step
FALSE

In [88]:
# imports
from tensorflow.keras.models import model_from_json


model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")

Saved model to disk